<a href="https://colab.research.google.com/github/Mayakshanesht/3d-deep-learning/blob/main/KalmanFilter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install filterpy

     |████████████████████████████████| 184kB 8.0MB/s 
  Created wheel for filterpy: filename=filterpy-1.4.5-cp37-none-any.whl size=110476 sha256=28dbacb82b2bbdc04be0851745347f5d85104bceed25d33490c944bc202a8828
  Stored in directory: /root/.cache/pip/wheels/c3/0c/dd/e92392c3f38a41371602d99fc77d6c1d42aadbf0c6afccdd02
Successfully built filterpy


In [2]:
from filterpy.kalman import KalmanFilter
from scipy.linalg import block_diag
from filterpy.common import Q_discrete_white_noise
import numpy as np

In [8]:
def OneDimensionKF(R_std, Q_std, dt):
    """ Create first order 2D Kalman filter."""
    kf = KalmanFilter(dim_x=2, dim_z=1)
    kf.x = np.zeros(2)
    kf.P = np.eye(2)*500
    kf.R = np.eye(1)*R_std**2
    kf.Q = Q_discrete_white_noise(dim=2,dt=dt,var=Q_std**2)
    kf.F = np.array([[1.,dt],[0.,1.]])
    kf.H = np.array([[1.,0.]])
    return kf

In [4]:
A=np.array([[25,0],[0,9]],dtype=float)
print(A)

[[25.  0.]
 [ 0.  9.]]


In [10]:
measurements = [1, 2, 3, 4, 5,6,7,8,9,10]
Q_std =5 # Experiment
R_std =10 # Experiment

dt = 1.

kf = OneDimensionKF(R_std, Q_std, dt)
for z in measurements:
    kf.predict()
    print("Predict...")
    print(kf.x)
    #print(kf.P)
    print("Measured: ",z)
    print("Update...")
    kf.update(z)
    print(kf.x)
    #print(kf.P)


Predict...
[0. 0.]
Measured:  1
Update...
[0.90960452 0.46327684]
Predict...
[1.37288136 0.46327684]
Measured:  2
Update...
[1.89139607 0.83947899]
Predict...
[2.73087507 0.83947899]
Measured:  3
Update...
[2.93494367 0.95479705]
Predict...
[3.88974071 0.95479705]
Measured:  4
Update...
[3.96571443 0.99222487]
Predict...
[4.9579393  0.99222487]
Measured:  5
Update...
[4.98523173 1.00525117]
Predict...
[5.9904829  1.00525117]
Measured:  6
Update...
[5.99650775 1.00814668]
Predict...
[7.00465443 1.00814668]
Measured:  7
Update...
[7.00172629 1.00672869]
Predict...
[8.00845497 1.00672869]
Measured:  8
Update...
[8.0031398 1.0041491]
Predict...
[9.00728891 1.0041491 ]
Measured:  9
Update...
[9.00270701 1.00192568]
Predict...
[10.00463269  1.00192568]
Measured:  10
Update...
[10.00172097  1.00051318]


In [7]:
def TwoDimensionsKF(R_std, Q_std, dt):
    """ Create first order Kalman filter. 
    Specify R and Q as floats."""
    kf = KalmanFilter(dim_x=4, dim_z=2)
    kf.x = np.zeros(4)
    kf.P = np.eye(4)*500
    kf.R = np.eye(2)*R_std**2
    q = Q_discrete_white_noise(dim=2,dt=dt,var=Q_std**2)
    kf.Q = block_diag(q, q)
    kf.F = np.array([[1,dt,0,0],
                     [0,1,0,0],
                     [0,0,1,dt],
                     [0,0,0,1]])
    kf.H = np.array([[1,0,0,0],
                    [0,0,1,0]])
    return kf

measurements = [(1,1), (2,2), (3,3), (4,4), (5,5)]
Q_std = 0.01
R_std = 5
dt = 1.

kf = TwoDimensionsKF(R_std, Q_std, dt)

for z in measurements:
    kf.predict()
    print("Predict...")
    print(kf.x)
    #print(kf.P)
    print("Measured: ",z)
    print("Update...")
    kf.update(z)
    print(kf.x)
    #print(kf.P)

Predict...
[0. 0. 0. 0.]
Measured:  (1, 1)
Update...
[0.97560976 0.48780491 0.97560976 0.48780491]
Predict...
[1.46341467 0.48780491 1.46341467 0.48780491]
Measured:  (2, 2)
Update...
[1.95933458 0.92421449 1.95933458 0.92421449]
Predict...
[2.88354907 0.92421449 2.88354907 0.92421449]
Measured:  (3, 3)
Update...
[2.97701572 0.97774543 2.97701572 0.97774543]
Predict...
[3.95476115 0.97774543 3.95476115 0.97774543]
Measured:  (4, 4)
Update...
[3.98571599 0.99066939 3.98571599 0.99066939]
Predict...
[4.97638538 0.99066939 4.97638538 0.99066939]
Measured:  (5, 5)
Update...
[4.99033074 0.99523621 4.99033074 0.99523621]


In [ ]:
from numpy import eye, zeros, isscalar, dot
import numpy as np
from filterpy.common import pretty_str, reshape_z
from copy import deepcopy

class CustomKalmanFilter():
    def __init__(self,dim_x, dim_z, dim_u=0):
        self.dim_x = dim_x
        self.dim_z = dim_z
        self.dim_u = dim_u

        self.x =
        self.P = 
        self.Q = 
        self.B = None                     # control transition matrix
        self.F = 
        self.H = 
        self.R = 
        self.M = 
        self.z = 

        # gain and residual are computed during the innovation step. We
        # save them so that in case you want to inspect them for various
        # purposes
        self.K = 
        self.y = 
        self.S = 
        self.SI = 

        # identity matrix. Do not alter this.
        self._I = 

        # these will always be a copy of x,P after predict() is called
        self.x_prior = self.x.copy()
        self.P_prior = self.P.copy()

        # these will always be a copy of x,P after update() is called
        self.x_post = self.x.copy()
        self.P_post = self.P.copy()

        self.inv = 

    def predict(self, u=None, B=None, F=None, Q=None):
        pass

    def update(self, z, R=None, H=None):
            pass

In [ ]:
kf = CustomKalmanFilter(4,2)
kf.x = np.array([[0, 0, 0, 0]]).T
kf.P = np.eye(4) * 500.
dt = 1.0
kf.F = np.array([[1, dt, 0,  0],
                [0,  1, 0,  0],
                [0,  0, 1, dt],
                [0,  0, 0,  1]])

kf.H = np.array([[1, 0, 0, 0],
                    [0, 0, 1, 0]])

from scipy.linalg import block_diag
from filterpy.common import Q_discrete_white_noise

q = Q_discrete_white_noise(dim=2, dt=dt, var=0.001)
kf.Q = block_diag(q, q)
kf.R = np.array([[5., 0],
                      [0, 5]])

zs = [[1, 1], [2,2], [3,3], [4,4]]
for z in zs:
    kf.predict(F=kf.F, Q=kf.Q)
    print("Prediction...")
    print("Predicted X")
    print(kf.x_prior)
    print("Predicted P")
    print(kf.P_prior)
    kf.update(z, R= kf.R, H = kf.H)
    print("Measurement... z = ")
    print(z)
    print("Updated X")
    print(kf.x_post)
    print("Updated P")
    print(kf.P_post)

In [ ]:
def SecondOrderKF(R_std, Q_std, dt, P=100):
    """ Create second order Kalman filter. 
    Specify R and Q as floats."""
    
    kf = KalmanFilter(dim_x=, dim_z=)
    kf.x = 
    kf.P = 
    kf.R = 
    kf.Q = 
    kf.F = 
    kf.H = 
    return kf

measurements = [1, 2, 3, 4, 5]
Q_std = 
R_std = 
dt = 1.

kf = SecondOrderKF(R_std, Q_std, dt)
for z in measurements:
    kf.predict()
    print("Predict...")
    print(kf.x)
    #print(kf.P)
    print("Measured: ",z)
    print("Update...")
    kf.update(z)
    print(kf.x)
    #print(kf.P)

In [ ]:
def SecondOrderKF(R_std, Q_std, dt, P=100):
    """ Create second order Kalman filter. 
    Specify R and Q as floats."""
    
    kf = KalmanFilter(dim_x=, dim_z=)
    kf.x = 
    kf.P = 
    kf.R = 
    kf.Q = Q_discrete_white_noise()
    kf.F = # The only big problem will be here, you must write the equations by hand to make sure you didn't do any mistake
    kf.H = 
    return kf

measurements = [(1,1), (2,2), (3,3), (4,4), (5,5)]
Q_std = 0.01
R_std = 5
dt = 1.

kf = SecondOrderKF(R_std, Q_std, dt)
for z in measurements:
    kf.predict()
    print("Predict...")
    print(kf.x)
    #print(kf.P)
    print("Measured: ",z)
    print("Update...")
    kf.update(z)
    print(kf.x)
    #print(kf.P)