<a href="https://colab.research.google.com/github/Mayakshanesht/3d-deep-learning/blob/main/KalmanFilter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install filterpy

     |████████████████████████████████| 184kB 6.3MB/s 
  Created wheel for filterpy: filename=filterpy-1.4.5-cp37-none-any.whl size=110476 sha256=96340a515bf9f4cb43c14b052c6147cedb31272139527a7ee9762f35a7a2fdae
  Stored in directory: /root/.cache/pip/wheels/c3/0c/dd/e92392c3f38a41371602d99fc77d6c1d42aadbf0c6afccdd02
Successfully built filterpy


In [2]:
from filterpy.kalman import KalmanFilter
from scipy.linalg import block_diag
from filterpy.common import Q_discrete_white_noise
import numpy as np

In [3]:
def OneDimensionKF(R_std, Q_std, dt):
    """ Create first order 2D Kalman filter."""
    kf = KalmanFilter(dim_x=2, dim_z=1)
    kf.x = np.zeros(2)
    kf.P = np.eye(2)*500
    kf.R = np.eye(1)*R_std**2
    kf.Q = Q_discrete_white_noise(dim=2,dt=dt,var=Q_std**2)
    kf.F = np.array([[1.,dt],[0.,1.]])
    kf.H = np.array([[1.,0.]])
    return kf

In [4]:
A=np.array([[25,0],[0,9]],dtype=float)
print(A)

[[25.  0.]
 [ 0.  9.]]


In [5]:
measurements = [1, 2, 3, 4, 5,6,7,8,9,10]
Q_std =5 # Experiment
R_std =10 # Experiment

dt = 1.

kf = OneDimensionKF(R_std, Q_std, dt)
for z in measurements:
    kf.predict()
    print("Predict...")
    print(kf.x)
    #print(kf.P)
    print("Measured: ",z)
    print("Update...")
    kf.update(z)
    print(kf.x)
    #print(kf.P)


Predict...
[0. 0.]
Measured:  1
Update...
[0.90960452 0.46327684]
Predict...
[1.37288136 0.46327684]
Measured:  2
Update...
[1.89139607 0.83947899]
Predict...
[2.73087507 0.83947899]
Measured:  3
Update...
[2.93494367 0.95479705]
Predict...
[3.88974071 0.95479705]
Measured:  4
Update...
[3.96571443 0.99222487]
Predict...
[4.9579393  0.99222487]
Measured:  5
Update...
[4.98523173 1.00525117]
Predict...
[5.9904829  1.00525117]
Measured:  6
Update...
[5.99650775 1.00814668]
Predict...
[7.00465443 1.00814668]
Measured:  7
Update...
[7.00172629 1.00672869]
Predict...
[8.00845497 1.00672869]
Measured:  8
Update...
[8.0031398 1.0041491]
Predict...
[9.00728891 1.0041491 ]
Measured:  9
Update...
[9.00270701 1.00192568]
Predict...
[10.00463269  1.00192568]
Measured:  10
Update...
[10.00172097  1.00051318]


In [6]:
def TwoDimensionsKF(R_std, Q_std, dt):
    """ Create first order Kalman filter. 
    Specify R and Q as floats."""
    kf = KalmanFilter(dim_x=4, dim_z=2)
    kf.x = np.zeros(4)
    kf.P = np.eye(4)*500
    kf.R = np.eye(2)*R_std**2
    q = Q_discrete_white_noise(dim=2,dt=dt,var=Q_std**2)
    kf.Q = block_diag(q, q)
    kf.F = np.array([[1,dt,0,0],
                     [0,1,0,0],
                     [0,0,1,dt],
                     [0,0,0,1]])
    kf.H = np.array([[1,0,0,0],
                    [0,0,1,0]])
    return kf

measurements = [(1,1), (2,2), (3,3), (4,4), (5,5)]
Q_std = 0.01
R_std = 5
dt = 1.

kf = TwoDimensionsKF(R_std, Q_std, dt)

for z in measurements:
    kf.predict()
    print("Predict...")
    print(kf.x)
    #print(kf.P)
    print("Measured: ",z)
    print("Update...")
    kf.update(z)
    print(kf.x)
    #print(kf.P)

Predict...
[0. 0. 0. 0.]
Measured:  (1, 1)
Update...
[0.97560976 0.48780491 0.97560976 0.48780491]
Predict...
[1.46341467 0.48780491 1.46341467 0.48780491]
Measured:  (2, 2)
Update...
[1.95933458 0.92421449 1.95933458 0.92421449]
Predict...
[2.88354907 0.92421449 2.88354907 0.92421449]
Measured:  (3, 3)
Update...
[2.97701572 0.97774543 2.97701572 0.97774543]
Predict...
[3.95476115 0.97774543 3.95476115 0.97774543]
Measured:  (4, 4)
Update...
[3.98571599 0.99066939 3.98571599 0.99066939]
Predict...
[4.97638538 0.99066939 4.97638538 0.99066939]
Measured:  (5, 5)
Update...
[4.99033074 0.99523621 4.99033074 0.99523621]


In [19]:
class CustomKalmanFilter():
  def __init__(self,dim_x,dim_z,dim_u=0):
    #dim_x=4
    #dim_z =2
    #dim_u = 0
    self.x = np.zeros(dim_x)
    self.P = np.eye(dim_x)*500
    Q_std = 0.01
    R_std = 5
    dt = 1.
    self.R = np.eye(dim_z)*R_std**2
    q = Q_discrete_white_noise(dim=dim_x/2,dt=dt,var=Q_std**2)
    self.Q = block_diag(q, q)
    self.F = np.array([[1,dt,0,0],
                     [0,1,0,0],
                     [0,0,1,dt],
                     [0,0,0,1]])
    self.H = np.array([[1,0,0,0],
                    [0,0,1,0]])
    self.y=np.zeros(dim_z)
    self.S=np.array([[0.,0.],[0.,0.]])
    self.K=np.zeros((dim_x,dim_z))
  
  def predict(self):
    self.x=np.dot(self.F,self.x)
    self.P=np.dot(np.dot(self.F,self.P),self.F.T)+self.Q

  def update(self,z):
    self.y=z-np.dot(self.H,self.x)
    self.S=np.dot(np.dot(self.H,self.P),self.H.T)+self.R
    self.K=np.dot(np.dot(self.P,self.H.T),np.linalg.inv(self.S))
    self.x+=np.dot(self.K,self.y)
    self.P=np.dot((np.eye(4)-np.dot(self.K,self.H)),self.P)

In [21]:
measurements = [(1,1), (2,2), (3,3), (4,4), (5,5),(7,7),(8,8),(9,9)]


kf = CustomKalmanFilter(4,2,0)

for z in measurements:
    kf.predict()
    print("Predict...")
    print(kf.x)
    #print(kf.P)
    print("Measured: ",z)
    print("Update...")
    kf.update(z)
    print(kf.x)
    #print(kf.P)

Predict...
[0. 0. 0. 0.]
Measured:  (1, 1)
Update...
[0.97560976 0.48780491 0.97560976 0.48780491]
Predict...
[1.46341467 0.48780491 1.46341467 0.48780491]
Measured:  (2, 2)
Update...
[1.95933458 0.92421449 1.95933458 0.92421449]
Predict...
[2.88354907 0.92421449 2.88354907 0.92421449]
Measured:  (3, 3)
Update...
[2.97701572 0.97774543 2.97701572 0.97774543]
Predict...
[3.95476115 0.97774543 3.95476115 0.97774543]
Measured:  (4, 4)
Update...
[3.98571599 0.99066939 3.98571599 0.99066939]
Predict...
[4.97638538 0.99066939 4.97638538 0.99066939]
Measured:  (5, 5)
Update...
[4.99033074 0.99523621 4.99033074 0.99523621]
Predict...
[5.98556695 0.99523621 5.98556695 0.99523621]
Measured:  (7, 7)
Update...
[6.51055135 1.1365281  6.51055135 1.1365281 ]
Predict...
[7.64707945 1.1365281  7.64707945 1.1365281 ]
Measured:  (8, 8)
Update...
[7.8093517  1.17358337 7.8093517  1.17358337]
Predict...
[8.98293507 1.17358337 8.98293507 1.17358337]
Measured:  (9, 9)
Update...
[8.98998813 1.17498178 8.98998

In [27]:
class SecondOrderKF():
  def __init__(self,dim_x,dim_z,dim_u=0):
    #dim_x=4
    #dim_z =2
    #dim_u = 0
    self.x = np.zeros(dim_x)
    self.P = np.eye(dim_x)*500
    Q_std = 0.01
    R_std = 5
    dt = 1.
    self.R = np.eye(dim_z)*R_std**2
    self.Q = Q_discrete_white_noise(dim=dim_x,dt=dt,var=Q_std**2)
    #self.Q = block_diag(q, q)
    self.F = np.array([[1,dt,0.5*dt**2],
                     [0,1,dt],
                     [0,0,1]])
    self.H = np.array([[1,0,0]])
    self.y=np.zeros(dim_z)
    self.S=np.array([[0.,0.],[0.,0.]])
    self.K=np.zeros((dim_x,dim_z))
  
  def predict(self):
    self.x=np.dot(self.F,self.x)
    self.P=np.dot(np.dot(self.F,self.P),self.F.T)+self.Q

  def update(self,z):
    self.y=z-np.dot(self.H,self.x)
    self.S=np.dot(np.dot(self.H,self.P),self.H.T)+self.R
    self.K=np.dot(np.dot(self.P,self.H.T),np.linalg.inv(self.S))
    self.x+=np.dot(self.K,self.y)
    self.P=np.dot((np.eye(3)-np.dot(self.K,self.H)),self.P)

In [29]:
measurements = [1, 2, 3, 4,6,8,10,12,14,17,20]

kf = SecondOrderKF(3,1,0)
for z in measurements:
    kf.predict()
    print("Predict...")
    print(kf.x)
    print(kf.P)
    print("Measured: ",z)
    print("Update...")
    kf.update(z)
    print(kf.x)
    print(kf.P)

Predict...
[0. 0. 0.]
[[1125.000025  750.00005   250.00005 ]
 [ 750.00005  1000.0001    500.0001  ]
 [ 250.00005   500.0001    500.0001  ]]
Measured:  1
Update...
[0.97826087 0.65217394 0.21739134]
[[ 24.45652175  16.30434856   5.43478358]
 [ 16.30434856 510.86961063 336.95658181]
 [  5.43478358 336.95658181 445.65225336]]
Predict...
[1.73913048 0.86956529 0.21739134]
[[1021.73928322 1260.86979216  565.21754206]
 [1260.86979216 1630.4351276   782.60893516]
 [ 565.21754206  782.60893516  445.65235336]]
Measured:  2
Update...
[1.99376947 1.18380064 0.35825548]
[[ 24.40290767  30.1142274   13.49948242]
 [ 30.1142274  111.63034187 101.76535147]
 [ 13.49948242 101.76535147 140.44658247]]
Predict...
[3.35669786 1.54205612 0.35825548]
[[346.63820885 378.11542013 185.48817512]
 [378.11542013 455.60772728 242.21203394]
 [185.48817512 242.21203394 140.44668247]]
Measured:  3
Update...
[3.02399497 1.17914145 0.18022418]
[[23.31825688 25.43572022 12.47773848]
 [25.43572022 70.90220579 53.49102088]