<a href="https://colab.research.google.com/github/Mayakshanesht/3d-deep-learning/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torchvision

In [ ]:
def activation(x):
  return 1/(1+torch.exp(-x))

In [ ]:
torch.manual_seed(7)
features=torch.randn(1,5)
weights=torch.randn_like(features)

bias=torch.randn(1,1)

In [ ]:
print(features,weights,bias)

tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]]) tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]]) tensor([[0.3177]])


In [ ]:
import numpy as np
#weights.resize_(5,1)
np.shape(weights)


torch.Size([1, 5])

In [ ]:
np.shape(features)

torch.Size([1, 5])

In [ ]:
def feedforward(features,weights,bias):
  
  y1=torch.mm(features,weights.view(5,1))
  #y1=torch.sum(features*weights)
  return activation(y1+bias)

In [ ]:
y=feedforward(features=features,weights=weights,bias=bias)

In [ ]:
print(y)

tensor([[0.1595]])


In [ ]:
features1=torch.randn(1,3)
n_input=features1.shape[1]
n_hidden=2
n_output=1
W1=torch.randn(n_input,n_hidden)
W2=torch.randn(n_hidden,n_output)
B1=torch.randn(1,n_hidden)
B2=torch.randn(1,n_output)

In [ ]:
h1=activation(torch.mm(features1,W1)+B1)
h2=activation(torch.mm(h1,W2)+B2)

In [ ]:
print(h2)

tensor([[0.8805]])


In [ ]:
import torch
from torch import nn, optim
import torch.autograd as grad
from torchvision import datasets, models, transforms

In [ ]:
import torch.nn.functional as F

In [ ]:
class Model(nn.Module):
  def __init__(self):
    super(Model,self).__init__()
    self.fc1=nn.Linear(784,256)
    self.fc2=nn.Linear(256,64)
    self.fc3=nn.Linear(64,10)
  
  def forward(self,x):
    x=x.view(x.shape[0],-1)
    x=F.relu(self.fc1(x))
    x=F.relu(self.fc2(x))
    x=nn.Log_Softmax(self.fc3(x),dim=1)
    return x
    

In [ ]:
import torch
from torch import nn
import torch.nn.functional as F
from torchvision import datasets, transforms

In [ ]:
# Define a transform to normalize the data
transform = transforms.Compose([transforms.ToTensor(),
                                transforms.Normalize((0.5,), (0.5,)),
                              ])

In [ ]:
trainset = datasets.MNIST('~/.pytorch/MNIST_data/', download=True, train=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)

  0%|          | 0/9912422 [00:00<?, ?it/s]

Extracting /root/.pytorch/MNIST_data/MNIST/raw/train-images-idx3-ubyte.gz to /root/.pytorch/MNIST_data/MNIST/raw



  0%|          | 0/28881 [00:00<?, ?it/s]

Extracting /root/.pytorch/MNIST_data/MNIST/raw/train-labels-idx1-ubyte.gz to /root/.pytorch/MNIST_data/MNIST/raw



  0%|          | 0/1648877 [00:00<?, ?it/s]

Extracting /root/.pytorch/MNIST_data/MNIST/raw/t10k-images-idx3-ubyte.gz to /root/.pytorch/MNIST_data/MNIST/raw



  0%|          | 0/4542 [00:00<?, ?it/s]

Extracting /root/.pytorch/MNIST_data/MNIST/raw/t10k-labels-idx1-ubyte.gz to /root/.pytorch/MNIST_data/MNIST/raw



/usr/local/lib/python3.7/dist-packages/torchvision/datasets/mnist.py:498: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:180.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)


In [ ]:
# Build a feed-forward network
model = nn.Sequential(nn.Linear(784, 128),
                      nn.ReLU(),
                      nn.Linear(128, 64),
                      nn.ReLU(),
                      nn.Linear(64, 10))

In [ ]:
# Define the loss
criterion = nn.CrossEntropyLoss()

In [ ]:
# Get our data
images, labels = next(iter(trainloader))

In [ ]:
# Flatten images
images = images.view(images.shape[0], -1)

In [ ]:
# Forward pass, get our logits
logits = model(images)

In [ ]:
model = nn.Sequential(nn.Linear(784, 128),
                      nn.ReLU(),
                      nn.Linear(128, 64),
                      nn.ReLU(),
                      nn.Linear(64, 10),
                      nn.LogSoftmax(dim=1))

criterion = nn.NLLLoss()
optimizer = optim.SGD(model.parameters(), lr=0.003)


In [ ]:
epochs = 5
for e in range(epochs):
    running_loss = 0
    for images, labels in trainloader:
        # Flatten MNIST images into a 784 long vector
        images = images.view(images.shape[0], -1)
    
        # TODO: Training pass
        optimizer.zero_grad()
        
        output = model(images)
        loss = criterion(output, labels)
        loss.backward()
        optimizer.step()
        
        running_loss += loss.item()
    else:
        print(f"Training loss: {running_loss/len(trainloader)}")

Training loss: 1.8926939823225872
Training loss: 0.8463982239778616
Training loss: 0.5314159400935875
Training loss: 0.43541539290439346
Training loss: 0.3890408780942085


In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline
import helper


In [ ]:
images, labels = next(iter(trainloader))

In [ ]:
img = images[1].view(1, 784)

In [ ]:
# Turn off gradients to speed up this part
with torch.no_grad():
    logps = model(img)

In [ ]:
# Output of the network are log-probabilities, need to take exponential for probabilities
ps = torch.exp(logps)
print(ps)

tensor([[9.4286e-07, 6.9993e-06, 1.0705e-05, 5.4786e-04, 1.6160e-05, 1.7603e-05,
         1.9329e-08, 9.8872e-01, 9.1993e-06, 1.0666e-02]])


In [ ]:
prob,idx=ps.topk(ps,1,dim=1)

In [ ]:
print(prob,idx)

tensor([[0.9887]]) tensor([[7]])


In [ ]:
#lets see how can we implement a transfer learning here
#step 1 import all the packages
import torch
from torch import nn, optim
import torch.nn.functional as F
import torchvision
from torchvision import transforms, datasets, models
import torch.autograd as grad


In [ ]:
#step 2 import all datasets and perform preprocessing on an input data
transform=transforms.Compose([transforms.ToTensor(),transforms.Normalize((0.5),(0.5))])
trainset=datasets.MNIST('~/.pytorch/MNIST',download=True, train=True, transform=transform)
testset=datasets.MNIST('~/.pytorch/MNIST',download=True, train=False, transform=transform)
Trainloader=torch.utils.data.DataLoader(trainset,batch_size=64,shuffle=True)
Testloader=torch.utils.data.DataLoader(testset,batch_size=64,shuffle=True)

  0%|          | 0/9912422 [00:00<?, ?it/s]

Extracting /root/.pytorch/MNIST/MNIST/raw/train-images-idx3-ubyte.gz to /root/.pytorch/MNIST/MNIST/raw



  0%|          | 0/28881 [00:00<?, ?it/s]

Extracting /root/.pytorch/MNIST/MNIST/raw/train-labels-idx1-ubyte.gz to /root/.pytorch/MNIST/MNIST/raw



  0%|          | 0/1648877 [00:00<?, ?it/s]

Extracting /root/.pytorch/MNIST/MNIST/raw/t10k-images-idx3-ubyte.gz to /root/.pytorch/MNIST/MNIST/raw



  0%|          | 0/4542 [00:00<?, ?it/s]

Extracting /root/.pytorch/MNIST/MNIST/raw/t10k-labels-idx1-ubyte.gz to /root/.pytorch/MNIST/MNIST/raw



In [ ]:
#step 3 import pretrained model and also write down a custom network
class Model(nn.Module):
  def __init__(self):
    super(Model,self).__init__()
    self.fc1=nn.Linear(784,512)
    self.fc2=nn.Linear(512,128)
    self.fc3=nn.Linear(128,10)
    self.dropout1=nn.Dropout(p=0.2)
    self.dropout2=nn.Dropout(p=0.2)
    self.logsoftmax=nn.LogSoftmax(dim=1)

  def forward(self,x):
    
    x=F.relu(self.dropout1(self.fc1(x)))
    x=F.relu(self.dropout2(self.fc2(x)))
    x=self.logsoftmax(self.fc3(x))
    return x


In [ ]:
model1=Model()
model1

Model(
  (fc1): Linear(in_features=784, out_features=512, bias=True)
  (fc2): Linear(in_features=512, out_features=128, bias=True)
  (fc3): Linear(in_features=128, out_features=10, bias=True)
  (dropout1): Dropout(p=0.2, inplace=False)
  (dropout2): Dropout(p=0.2, inplace=False)
  (logsoftmax): LogSoftmax(dim=1)
)

In [ ]:
backbone=models.resnet50(pretrained=True)
for param in backbone.parameters():
  param.required_grad=False

Downloading: "https://download.pytorch.org/models/resnet50-0676ba61.pth" to /root/.cache/torch/hub/checkpoints/resnet50-0676ba61.pth


  0%|          | 0.00/97.8M [00:00<?, ?B/s]

In [ ]:
backbone.fc=model1


In [ ]:
backbone

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 

In [ ]:
device=torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [ ]:
for images, labels in Trainloader:
  print(images.shape,labels.shape)

torch.Size([64, 1, 28, 28]) torch.Size([64])
torch.Size([64, 1, 28, 28]) torch.Size([64])
torch.Size([64, 1, 28, 28]) torch.Size([64])
torch.Size([64, 1, 28, 28]) torch.Size([64])
torch.Size([64, 1, 28, 28]) torch.Size([64])
torch.Size([64, 1, 28, 28]) torch.Size([64])
torch.Size([64, 1, 28, 28]) torch.Size([64])
torch.Size([64, 1, 28, 28]) torch.Size([64])
torch.Size([64, 1, 28, 28]) torch.Size([64])
torch.Size([64, 1, 28, 28]) torch.Size([64])
torch.Size([64, 1, 28, 28]) torch.Size([64])
torch.Size([64, 1, 28, 28]) torch.Size([64])
torch.Size([64, 1, 28, 28]) torch.Size([64])
torch.Size([64, 1, 28, 28]) torch.Size([64])
torch.Size([64, 1, 28, 28]) torch.Size([64])
torch.Size([64, 1, 28, 28]) torch.Size([64])
torch.Size([64, 1, 28, 28]) torch.Size([64])
torch.Size([64, 1, 28, 28]) torch.Size([64])
torch.Size([64, 1, 28, 28]) torch.Size([64])
torch.Size([64, 1, 28, 28]) torch.Size([64])
torch.Size([64, 1, 28, 28]) torch.Size([64])
torch.Size([64, 1, 28, 28]) torch.Size([64])
torch.Size

In [ ]:
#Step 4 Now develop a pipeline to train a model
model1.to(device);
optimizer=optim.Adam(model1.parameters(),lr=0.001)
criterion=nn.NLLLoss()
epochs=10
for i in range(epochs):
  runningLoss=0
  for images, labels in Trainloader:
    images,labels=images.to(device),labels.to(device)
    images=images.view(images.shape[0],784)
    optimizer.zero_grad()
    outputs=model1.forward(images)
    loss=criterion(outputs,labels)
    loss.backward()
    optimizer.step()
    runningLoss+=loss.item()
    print('runningLoss:{}'.format(runningLoss/len(Trainloader)))


Streaming output truncated to the last 5000 lines.
runningLoss:0.0775856448502254
runningLoss:0.07780503388394965
runningLoss:0.07788106998992658
runningLoss:0.07808870980754368
runningLoss:0.07819624671410681
runningLoss:0.0782897335413629
runningLoss:0.07838285140601843
runningLoss:0.07861734975649635
runningLoss:0.0788335727223916
runningLoss:0.07891667298754172
runningLoss:0.07901588504585916
runningLoss:0.0791673263731494
runningLoss:0.0793407707900079
runningLoss:0.0794472489992518
runningLoss:0.07951273678291614
runningLoss:0.07960283222979606
runningLoss:0.07970037251444799
runningLoss:0.07973062687777857
runningLoss:0.07986787326042173
runningLoss:0.08000960390764608
runningLoss:0.08013733528725216
runningLoss:0.08020884020905346
runningLoss:0.0803901478955979
runningLoss:0.0805439698343068
runningLoss:0.08063900764527193
runningLoss:0.08065782581219699
runningLoss:0.080881323769633
runningLoss:0.08101372374023107
runningLoss:0.08118123744727611
runningLoss:0.08130813885762143

In [ ]:
with torch.no_grad():
  testLoss=0
  model1.eval()
  for images, labels in Testloader:
    images,labels=images.to(device),labels.to(device)
    images=images.view(images.shape[0],784)
    
    outputs=model1.forward(images)
    loss=criterion(outputs,labels)
    testLoss+=loss.item()
    print('runningLoss:{}'.format(testLoss/len(Testloader)))


runningLoss:0.0009499693372447019
runningLoss:0.0011996451029731969
runningLoss:0.0015675263230208378
runningLoss:0.0017180000758095153
runningLoss:0.0021851370051787916
runningLoss:0.0030380902918660715
runningLoss:0.0038697938583079415
runningLoss:0.004445508715643245
runningLoss:0.004735972874673309
runningLoss:0.0047769613154707066
runningLoss:0.00569260853289324
runningLoss:0.006018143879831027
runningLoss:0.006843822726469701
runningLoss:0.007113394793123007
runningLoss:0.008267026462823531
runningLoss:0.008797862107278245
runningLoss:0.009088437953833371
runningLoss:0.009205882820140595
runningLoss:0.00968075520803879
runningLoss:0.010425319393895044
runningLoss:0.010629409256800535
runningLoss:0.011438195406797396
runningLoss:0.011887493463244978
runningLoss:0.012554609053619917
runningLoss:0.013056348377518403
runningLoss:0.014065855161945341
runningLoss:0.014303568712061947
runningLoss:0.014552830211272474
runningLoss:0.015255005149301261
runningLoss:0.015366903093946019
runn

In [ ]:
torch.save(model1,'MNIST.pth')

In [ ]:
model=torch.load('MNIST.pth')
model.to(device)

Model(
  (fc1): Linear(in_features=784, out_features=512, bias=True)
  (fc2): Linear(in_features=512, out_features=128, bias=True)
  (fc3): Linear(in_features=128, out_features=10, bias=True)
  (dropout1): Dropout(p=0.2, inplace=False)
  (dropout2): Dropout(p=0.2, inplace=False)
  (logsoftmax): LogSoftmax(dim=1)
)

In [ ]:
images,labels=next(iter(Testloader))
images,labels=images.to(device),labels.to(device)
img=images[10].view(1,784)
out=model(img)

In [ ]:
ps=torch.exp(out)
prob,idx=ps.topk(1,dim=1)

In [ ]:
print(idx,prob)

tensor([[8]], device='cuda:0') tensor([[0.9996]], device='cuda:0', grad_fn=<TopkBackward>)
